// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type AboutPageDocumentDataSlicesSlice = never;

/**
 * Content for about_page documents
 */
interface AboutPageDocumentData {
  /**
   * Page Title field in *about_page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: about_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Hero Image field in *about_page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Artist Name field in *about_page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Artist name
   * - **API ID Path**: about_page.artist_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  artist_name: prismic.KeyTextField;

  /**
   * Bio field in *about_page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Artist biography
   * - **API ID Path**: about_page.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  bio: prismic.RichTextField;

  /**
   * `slices` field in *about_page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice>;
}

/**
 * about_page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

/**
 * Content for Bandsintown Configuration documents
 */
interface BandsintownConfigDocumentData {
  /**
   * Artist Name field in *Bandsintown Configuration*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Enter the exact artist name as it appears on Bandsintown
   * - **API ID Path**: bandsintown_config.artist_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  artist_name: prismic.KeyTextField;

  /**
   * Bandsintown App ID (Optional) field in *Bandsintown Configuration*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Your Bandsintown app ID for higher rate limits
   * - **API ID Path**: bandsintown_config.app_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  app_id: prismic.KeyTextField;

  /**
   * Enable Bandsintown Integration field in *Bandsintown Configuration*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: bandsintown_config.enable_bandsintown
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  enable_bandsintown: prismic.BooleanField;

  /**
   * Fallback Message field in *Bandsintown Configuration*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Message to display when no events are available
   * - **API ID Path**: bandsintown_config.fallback_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  fallback_message: prismic.RichTextField;
}

/**
 * Bandsintown Configuration document from Prismic
 *
 * - **API ID**: `bandsintown_config`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type BandsintownConfigDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<BandsintownConfigDocumentData>,
    "bandsintown_config",
    Lang
  >;

/**
 * Content for contact documents
 */
interface ContactDocumentData {
  /**
   * Contact Name field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_name: prismic.KeyTextField;

  /**
   * Contact Page Title field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_title: prismic.KeyTextField;

  /**
   * Contact Email field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * Contact Message field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Hello...
   * - **API ID Path**: contact.contact_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_message: prismic.KeyTextField;

  /**
   * Submit Button Text field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.submit_button_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_button_text: prismic.KeyTextField;

  /**
   * Success Message field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.success_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  success_message: prismic.KeyTextField;

  /**
   * Failure Message field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.failure_message
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  failure_message: prismic.KeyTextField;

  /**
   * Contact Phone field in *contact*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.contact_phone
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_phone: prismic.KeyTextField;
}

/**
 * contact document from Prismic
 *
 * - **API ID**: `contact`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactDocumentData>,
    "contact",
    Lang
  >;

type ContactInfoDocumentDataSlicesSlice = ContactSlice;

/**
 * Content for Contact info documents
 */
interface ContactInfoDocumentData {
  /**
   * Slice Zone field in *Contact info*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ContactInfoDocumentDataSlicesSlice> /**
   * Meta Title field in *Contact info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: contact_info.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Contact info*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: contact_info.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Contact info*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: contact_info.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Contact info document from Prismic
 *
 * - **API ID**: `contact_info`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ContactInfoDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ContactInfoDocumentData>,
    "contact_info",
    Lang
  >;

type EventDocumentDataSlicesSlice = never;

/**
 * Content for event documents
 */
interface EventDocumentData {
  /**
   * date field in *event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * venue field in *event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.venue
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  venue: prismic.KeyTextField;

  /**
   * location field in *event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * ticket_link field in *event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.ticket_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  ticket_link: prismic.KeyTextField;

  /**
   * description field in *event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Slice Zone field in *event*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: event.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<EventDocumentDataSlicesSlice>;
}

/**
 * event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<EventDocumentData>, "event", Lang>;

type HomepageDocumentDataSlicesSlice =
  | BackgroundVideoSlice
  | HeroSectionSlice
  | FeaturedReleasesSlice
  | UpcomingEventsSlice
  | ReleaseCardSlice
  | EventItemSlice
  | ProductCarouselSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * hero_image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * featured_text field in *homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.featured_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  featured_text: prismic.RichTextField;

  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type MediaPageDocumentDataSlicesSlice =
  | VideoCarouselSlice
  | InstagramGallerySlice;

/**
 * Content for Media Page documents
 */
interface MediaPageDocumentData {
  /**
   * Page Title field in *Media Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Media
   * - **API ID Path**: media_page.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Media Page Slices field in *Media Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: media_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<MediaPageDocumentDataSlicesSlice>;
}

/**
 * Media Page document from Prismic
 *
 * - **API ID**: `media_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type MediaPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<MediaPageDocumentData>,
    "media_page",
    Lang
  >;

/**
 * Item in *release → links*
 */
export interface ReleaseDocumentDataLinksItem {
  /**
   * platform_name field in *release → links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: release.links[].platform_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform_name: prismic.KeyTextField;

  /**
   * url field in *release → links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: release.links[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type ReleaseDocumentDataSlicesSlice = VideoCarouselSlice;

/**
 * Content for release documents
 */
interface ReleaseDocumentData {
  /**
   * title field in *release*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: release.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * cover_image field in *release*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: release.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * release_date field in *release*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: release.release_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  release_date: prismic.DateField;

  /**
   * description field in *release*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: release.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * links field in *release*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: release.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  links: prismic.GroupField<Simplify<ReleaseDocumentDataLinksItem>>;

  /**
   * Slice Zone field in *release*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: release.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ReleaseDocumentDataSlicesSlice>;
}

/**
 * release document from Prismic
 *
 * - **API ID**: `release`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReleaseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReleaseDocumentData>,
    "release",
    Lang
  >;

type ReleasesDocumentDataSlicesSlice = FeaturedReleasesSlice;

/**
 * Content for Releases documents
 */
interface ReleasesDocumentData {
  /**
   * Slice Zone field in *Releases*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<ReleasesDocumentDataSlicesSlice> /**
   * Meta Title field in *Releases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: releases.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Releases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: releases.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Releases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Releases document from Prismic
 *
 * - **API ID**: `releases`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReleasesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReleasesDocumentData>,
    "releases",
    Lang
  >;

/**
 * Item in *site_settings → social_links*
 */
export interface SiteSettingsDocumentDataSocialLinksItem {}

type SiteSettingsDocumentDataSlicesSlice = never;

/**
 * Content for site_settings documents
 */
interface SiteSettingsDocumentData {
  /**
   * artist_name field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.artist_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  artist_name: prismic.KeyTextField;

  /**
   * contact_email field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Email address to receive contact form submissions
   * - **API ID Path**: site_settings.contact_email
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_email: prismic.KeyTextField;

  /**
   * social_links field in *site_settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  social_links: prismic.GroupField<
    Simplify<SiteSettingsDocumentDataSocialLinksItem>
  >;

  /**
   * platform field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.platform
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform: prismic.KeyTextField;

  /**
   * url field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  url: prismic.KeyTextField;

  /**
   * enable_bandsintown field in *site_settings*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: true
   * - **API ID Path**: site_settings.enable_bandsintown
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  enable_bandsintown: prismic.BooleanField;

  /**
   * bandsintown_api_id field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.bandsintown_api_id
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bandsintown_api_id: prismic.KeyTextField;

  /**
   * bandsintown_artist_name field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.bandsintown_artist_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  bandsintown_artist_name: prismic.KeyTextField;

  /**
   * stripe_public_api_key field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.stripe_public_api_key
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stripe_public_api_key: prismic.KeyTextField;

  /**
   * stripe_private_api_key field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.stripe_private_api_key
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stripe_private_api_key: prismic.KeyTextField;

  /**
   * resend_api_key field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.resend_api_key
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  resend_api_key: prismic.KeyTextField;

  /**
   * background_video_url field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.background_video_url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  background_video_url: prismic.KeyTextField;

  /**
   * Slice Zone field in *site_settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<SiteSettingsDocumentDataSlicesSlice>;
}

/**
 * site_settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteSettingsDocumentData>,
    "site_settings",
    Lang
  >;

type TourPageDocumentDataSlicesSlice = UpcomingEventsSlice | HeroSectionSlice;

/**
 * Content for Tour Page documents
 */
interface TourPageDocumentData {
  /**
   * Page Title field in *Tour Page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Tour
   * - **API ID Path**: tour_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  page_title: prismic.KeyTextField;

  /**
   * Page Description field in *Tour Page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Enter a description for the tour page
   * - **API ID Path**: tour_page.page_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  page_description: prismic.RichTextField;

  /**
   * Tour Page Slices field in *Tour Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: tour_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<TourPageDocumentDataSlicesSlice>;
}

/**
 * Tour Page document from Prismic
 *
 * - **API ID**: `tour_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type TourPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<TourPageDocumentData>,
    "tour_page",
    Lang
  >;

export type AllDocumentTypes =
  | AboutPageDocument
  | BandsintownConfigDocument
  | ContactDocument
  | ContactInfoDocument
  | EventDocument
  | HomepageDocument
  | MediaPageDocument
  | ReleaseDocument
  | ReleasesDocument
  | SiteSettingsDocument
  | TourPageDocument;

/**
 * Item in *AlternateGrid → Default → Primary → items*
 */
export interface AlternateGridSliceDefaultPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Item in *AlternateGrid → Image Right → Primary → items*
 */
export interface AlternateGridSliceImageRightPrimaryItemsItem {
  /**
   * title field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary → items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *AlternateGrid → Default → Primary*
 */
export interface AlternateGridSliceDefaultPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.default.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.default.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceDefaultPrimaryItemsItem>
  >;
}

/**
 * Default variation for AlternateGrid Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlternateGridSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<AlternateGridSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *AlternateGrid → Image Right → Primary*
 */
export interface AlternateGridSliceImageRightPrimary {
  /**
   * eyebrowHeadline field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Eyebrow
   * - **API ID Path**: alternate_grid.imageRight.primary.eyebrowHeadline
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  eyebrowHeadline: prismic.KeyTextField;

  /**
   * title field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  title: prismic.RichTextField;

  /**
   * description field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * image field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * items field in *AlternateGrid → Image Right → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: alternate_grid.imageRight.primary.items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  items: prismic.GroupField<
    Simplify<AlternateGridSliceImageRightPrimaryItemsItem>
  >;
}

/**
 * Image Right variation for AlternateGrid Slice
 *
 * - **API ID**: `imageRight`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlternateGridSliceImageRight = prismic.SharedSliceVariation<
  "imageRight",
  Simplify<AlternateGridSliceImageRightPrimary>,
  never
>;

/**
 * Slice variation for *AlternateGrid*
 */
type AlternateGridSliceVariation =
  | AlternateGridSliceDefault
  | AlternateGridSliceImageRight;

/**
 * AlternateGrid Shared Slice
 *
 * - **API ID**: `alternate_grid`
 * - **Description**: AlternateGrid
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type AlternateGridSlice = prismic.SharedSlice<
  "alternate_grid",
  AlternateGridSliceVariation
>;

/**
 * Primary content in *BackgroundVideo → Default → Primary*
 */
export interface BackgroundVideoSliceDefaultPrimary {
  /**
   * Background Video URL field in *BackgroundVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: background_video.default.primary.background_video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  background_video_url: prismic.KeyTextField;

  /**
   * video provider field in *BackgroundVideo → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: background_video.default.primary.video_provider
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_provider: prismic.KeyTextField;

  /**
   * background image field in *BackgroundVideo → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: background_video.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;
}

/**
 * Default variation for BackgroundVideo Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BackgroundVideoSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<BackgroundVideoSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *BackgroundVideo*
 */
type BackgroundVideoSliceVariation = BackgroundVideoSliceDefault;

/**
 * BackgroundVideo Shared Slice
 *
 * - **API ID**: `background_video`
 * - **Description**: BackgroundVideo
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type BackgroundVideoSlice = prismic.SharedSlice<
  "background_video",
  BackgroundVideoSliceVariation
>;

/**
 * Primary content in *Contact → Default → Primary*
 */
export interface ContactSliceDefaultPrimary {
  /**
   * Name field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  name: prismic.KeyTextField;

  /**
   * Email field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.email
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  email: prismic.KeyTextField;

  /**
   * Subject field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.subject
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subject: prismic.KeyTextField;

  /**
   * Message field in *Contact → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.message
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  message: prismic.RichTextField;

  /**
   * Submit Button Name field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.submit_button_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  submit_button_name: prismic.KeyTextField;

  /**
   * Contact Error Message field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_error_message
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_error_message: prismic.KeyTextField;

  /**
   * Contact Success Message field in *Contact → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: contact.default.primary.contact_success_message
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  contact_success_message: prismic.KeyTextField;
}

/**
 * Default variation for Contact Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ContactSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *Contact*
 */
type ContactSliceVariation = ContactSliceDefault;

/**
 * Contact Shared Slice
 *
 * - **API ID**: `contact`
 * - **Description**: Contact
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ContactSlice = prismic.SharedSlice<
  "contact",
  ContactSliceVariation
>;

/**
 * Primary content in *EventItem → Default → Primary*
 */
export interface EventItemSliceDefaultPrimary {
  /**
   * Event Date field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select event date
   * - **API ID Path**: event_item.default.primary.date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Venue field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Venue name
   * - **API ID Path**: event_item.default.primary.venue
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  venue: prismic.KeyTextField;

  /**
   * Location field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, State/Country
   * - **API ID Path**: event_item.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Ticket Link field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to tickets
   * - **API ID Path**: event_item.default.primary.ticket_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ticket_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Description field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Event description
   * - **API ID Path**: event_item.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for EventItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventItem*
 */
type EventItemSliceVariation = EventItemSliceDefault;

/**
 * EventItem Shared Slice
 *
 * - **API ID**: `event_item`
 * - **Description**: EventItem
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type EventItemSlice = prismic.SharedSlice<
  "event_item",
  EventItemSliceVariation
>;

/**
 * Primary content in *FeaturedReleases → Default → Primary*
 */
export interface FeaturedReleasesSliceDefaultPrimary {
  /**
   * Releases field in *FeaturedReleases → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Featured Releases
   * - **API ID Path**: featured_releases.default.primary.releases
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  releases: prismic.KeyTextField;

  /**
   * Section Description field in *FeaturedReleases → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description of the releases section
   * - **API ID Path**: featured_releases.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;
}

/**
 * Primary content in *FeaturedReleases → Items*
 */
export interface FeaturedReleasesSliceDefaultItem {
  /**
   * Title field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Release title
   * - **API ID Path**: featured_releases.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Cover Image field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_releases.items[].cover_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Release Date field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select release date
   * - **API ID Path**: featured_releases.items[].release_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  release_date: prismic.DateField;

  /**
   * Description field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Release description
   * - **API ID Path**: featured_releases.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Platform URL field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_releases.items[].platform_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  platform_url: prismic.Repeatable<
    prismic.LinkField<string, string, unknown, prismic.FieldState, never>
  >;
}

/**
 * Default variation for FeaturedReleases Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedReleasesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedReleasesSliceDefaultPrimary>,
  Simplify<FeaturedReleasesSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedReleases*
 */
type FeaturedReleasesSliceVariation = FeaturedReleasesSliceDefault;

/**
 * FeaturedReleases Shared Slice
 *
 * - **API ID**: `featured_releases`
 * - **Description**: FeaturedReleases
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type FeaturedReleasesSlice = prismic.SharedSlice<
  "featured_releases",
  FeaturedReleasesSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Main headline
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subtitle text
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description text
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;

  /**
   * Video URL (YouTube/Vimeo) field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://www.youtube.com/watch?v=... or https://vimeo.com/...
   * - **API ID Path**: hero_section.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_url: prismic.KeyTextField;

  /**
   * Background Image (fallback) field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  background_image: prismic.ImageField<never>;

  /**
   * CTA Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Call to action text
   * - **API ID Path**: hero_section.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call to action link
   * - **API ID Path**: hero_section.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *InstagramGallery → Default → Primary*
 */
export interface InstagramGallerySliceDefaultPrimary {
  /**
   * Instagram Username field in *InstagramGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g. zekeultra
   * - **API ID Path**: instagram_gallery.default.primary.instagram_username
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  instagram_username: prismic.KeyTextField;

  /**
   * Instagram Gallery Embed Code field in *InstagramGallery → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Paste your Instagram widget/embed code here.
   * - **API ID Path**: instagram_gallery.default.primary.embed_code
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  embed_code: prismic.RichTextField;
}

/**
 * Default variation for InstagramGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InstagramGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<InstagramGallerySliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *InstagramGallery*
 */
type InstagramGallerySliceVariation = InstagramGallerySliceDefault;

/**
 * InstagramGallery Shared Slice
 *
 * - **API ID**: `instagram_gallery`
 * - **Description**: A gallery grid of Instagram posts.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type InstagramGallerySlice = prismic.SharedSlice<
  "instagram_gallery",
  InstagramGallerySliceVariation
>;

/**
 * Primary content in *MediaGallery → Default → Primary*
 */
export interface MediaGallerySliceDefaultPrimary {
  /**
   * Gallery Title field in *MediaGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Gallery title
   * - **API ID Path**: media_gallery.default.primary.gallery_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  gallery_title: prismic.KeyTextField;
}

/**
 * Primary content in *MediaGallery → Items*
 */
export interface MediaGallerySliceDefaultItem {
  /**
   * Title field in *MediaGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Media item title
   * - **API ID Path**: media_gallery.items[].title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *MediaGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  image: prismic.ImageField<never>;

  /**
   * Video URL field in *MediaGallery → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Video URL
   * - **API ID Path**: media_gallery.items[].video_url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Embed Code field in *MediaGallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Paste embed code
   * - **API ID Path**: media_gallery.items[].embed_code
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  embed_code: prismic.RichTextField;
}

/**
 * Default variation for MediaGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaGallerySliceDefaultPrimary>,
  Simplify<MediaGallerySliceDefaultItem>
>;

/**
 * Slice variation for *MediaGallery*
 */
type MediaGallerySliceVariation = MediaGallerySliceDefault;

/**
 * MediaGallery Shared Slice
 *
 * - **API ID**: `media_gallery`
 * - **Description**: MediaGallery
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type MediaGallerySlice = prismic.SharedSlice<
  "media_gallery",
  MediaGallerySliceVariation
>;

/**
 * Primary content in *ProductCarousel → Default → Primary*
 */
export interface ProductCarouselSliceDefaultPrimary {
  /**
   * Section Title field in *ProductCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Featured Products
   * - **API ID Path**: product_carousel.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Use Stripe Products field in *ProductCarousel → Default → Primary*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: Automatically pull products from Stripe
   * - **Default Value**: true
   * - **API ID Path**: product_carousel.default.primary.use_stripe_products
   * - **Documentation**: https://prismic.io/docs/fields/boolean
   */
  use_stripe_products: prismic.BooleanField;
}

/**
 * Primary content in *ProductCarousel → Items*
 */
export interface ProductCarouselSliceDefaultItem {
  /**
   * Product ID field in *ProductCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: prod_123456789
   * - **API ID Path**: product_carousel.items[].product_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_id: prismic.KeyTextField;

  /**
   * Product Name field in *ProductCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Product Name
   * - **API ID Path**: product_carousel.items[].product_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_name: prismic.KeyTextField;

  /**
   * Product Description field in *ProductCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Product description...
   * - **API ID Path**: product_carousel.items[].product_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  product_description: prismic.KeyTextField;

  /**
   * Product Image field in *ProductCarousel → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: product_carousel.items[].product_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  product_image: prismic.ImageField<never>;

  /**
   * Product Price (in cents) field in *ProductCarousel → Items*
   *
   * - **Field Type**: Number
   * - **Placeholder**: 2500
   * - **API ID Path**: product_carousel.items[].product_price
   * - **Documentation**: https://prismic.io/docs/fields/number
   */
  product_price: prismic.NumberField;

  /**
   * Stripe Price ID field in *ProductCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: price_123456789
   * - **API ID Path**: product_carousel.items[].stripe_price_id
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  stripe_price_id: prismic.KeyTextField;

  /**
   * Currency field in *ProductCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: usd
   * - **API ID Path**: product_carousel.items[].currency
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  currency: prismic.KeyTextField;
}

/**
 * Default variation for ProductCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: ProductCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ProductCarouselSliceDefaultPrimary>,
  Simplify<ProductCarouselSliceDefaultItem>
>;

/**
 * Slice variation for *ProductCarousel*
 */
type ProductCarouselSliceVariation = ProductCarouselSliceDefault;

/**
 * ProductCarousel Shared Slice
 *
 * - **API ID**: `product_carousel`
 * - **Description**: ProductCarousel
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ProductCarouselSlice = prismic.SharedSlice<
  "product_carousel",
  ProductCarouselSliceVariation
>;

/**
 * Primary content in *ReleaseCard → Default → Primary*
 */
export interface ReleaseCardSliceDefaultPrimary {
  /**
   * Title field in *ReleaseCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Release title
   * - **API ID Path**: release_card.default.primary.title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  title: prismic.KeyTextField;

  /**
   * Cover Image field in *ReleaseCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: release_card.default.primary.cover_image
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Release Date field in *ReleaseCard → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select release date
   * - **API ID Path**: release_card.default.primary.release_date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  release_date: prismic.DateField;

  /**
   * Description field in *ReleaseCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Release description
   * - **API ID Path**: release_card.default.primary.description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ReleaseCard → Items*
 */
export interface ReleaseCardSliceDefaultItem {
  /**
   * Platform Name field in *ReleaseCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Spotify, Apple Music
   * - **API ID Path**: release_card.items[].platform_name
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  platform_name: prismic.KeyTextField;

  /**
   * URL field in *ReleaseCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to platform
   * - **API ID Path**: release_card.items[].url
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ReleaseCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReleaseCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReleaseCardSliceDefaultPrimary>,
  Simplify<ReleaseCardSliceDefaultItem>
>;

/**
 * Slice variation for *ReleaseCard*
 */
type ReleaseCardSliceVariation = ReleaseCardSliceDefault;

/**
 * ReleaseCard Shared Slice
 *
 * - **API ID**: `release_card`
 * - **Description**: ReleaseCard
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type ReleaseCardSlice = prismic.SharedSlice<
  "release_card",
  ReleaseCardSliceVariation
>;

/**
 * Primary content in *UpcomingEvents → Default → Primary*
 */
export interface UpcomingEventsSliceDefaultPrimary {
  /**
   * Section Title field in *UpcomingEvents → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Upcoming Events
   * - **API ID Path**: upcoming_events.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *UpcomingEvents → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description of upcoming events
   * - **API ID Path**: upcoming_events.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  section_description: prismic.RichTextField;

  /**
   * View All Text field in *UpcomingEvents → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View All Events
   * - **API ID Path**: upcoming_events.default.primary.view_all_text
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  view_all_text: prismic.KeyTextField;

  /**
   * View All Link field in *UpcomingEvents → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to all events page
   * - **API ID Path**: upcoming_events.default.primary.view_all_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  view_all_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *UpcomingEvents → Items*
 */
export interface UpcomingEventsSliceDefaultItem {
  /**
   * Event Date field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select event date
   * - **API ID Path**: upcoming_events.items[].date
   * - **Documentation**: https://prismic.io/docs/fields/date
   */
  date: prismic.DateField;

  /**
   * Venue field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Venue name
   * - **API ID Path**: upcoming_events.items[].venue
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  venue: prismic.KeyTextField;

  /**
   * Location field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, State/Country
   * - **API ID Path**: upcoming_events.items[].location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Ticket Link field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to tickets
   * - **API ID Path**: upcoming_events.items[].ticket_link
   * - **Documentation**: https://prismic.io/docs/fields/link
   */
  ticket_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Description field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Event description
   * - **API ID Path**: upcoming_events.items[].description
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for UpcomingEvents Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UpcomingEventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UpcomingEventsSliceDefaultPrimary>,
  Simplify<UpcomingEventsSliceDefaultItem>
>;

/**
 * Slice variation for *UpcomingEvents*
 */
type UpcomingEventsSliceVariation = UpcomingEventsSliceDefault;

/**
 * UpcomingEvents Shared Slice
 *
 * - **API ID**: `upcoming_events`
 * - **Description**: UpcomingEvents
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type UpcomingEventsSlice = prismic.SharedSlice<
  "upcoming_events",
  UpcomingEventsSliceVariation
>;

/**
 * Primary content in *VideoCarousel → Default → Primary*
 */
export interface VideoCarouselSliceDefaultPrimary {
  /**
   * Section Title field in *VideoCarousel → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Featured Videos
   * - **API ID Path**: video_carousel.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;
}

/**
 * Primary content in *VideoCarousel → Items*
 */
export interface VideoCarouselSliceDefaultItem {
  /**
   * Video Embed URL field in *VideoCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: YouTube or Vimeo URL
   * - **API ID Path**: video_carousel.items[].video_url
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  video_url: prismic.KeyTextField;

  /**
   * Caption field in *VideoCarousel → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Optional caption for the video
   * - **API ID Path**: video_carousel.items[].caption
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  caption: prismic.KeyTextField;
}

/**
 * Default variation for VideoCarousel Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoCarouselSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VideoCarouselSliceDefaultPrimary>,
  Simplify<VideoCarouselSliceDefaultItem>
>;

/**
 * Slice variation for *VideoCarousel*
 */
type VideoCarouselSliceVariation = VideoCarouselSliceDefault;

/**
 * VideoCarousel Shared Slice
 *
 * - **API ID**: `video_carousel`
 * - **Description**: A widescreen carousel for video embeds.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type VideoCarouselSlice = prismic.SharedSlice<
  "video_carousel",
  VideoCarouselSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      BandsintownConfigDocument,
      BandsintownConfigDocumentData,
      ContactDocument,
      ContactDocumentData,
      ContactInfoDocument,
      ContactInfoDocumentData,
      ContactInfoDocumentDataSlicesSlice,
      EventDocument,
      EventDocumentData,
      EventDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      MediaPageDocument,
      MediaPageDocumentData,
      MediaPageDocumentDataSlicesSlice,
      ReleaseDocument,
      ReleaseDocumentData,
      ReleaseDocumentDataLinksItem,
      ReleaseDocumentDataSlicesSlice,
      ReleasesDocument,
      ReleasesDocumentData,
      ReleasesDocumentDataSlicesSlice,
      SiteSettingsDocument,
      SiteSettingsDocumentData,
      SiteSettingsDocumentDataSocialLinksItem,
      SiteSettingsDocumentDataSlicesSlice,
      TourPageDocument,
      TourPageDocumentData,
      TourPageDocumentDataSlicesSlice,
      AllDocumentTypes,
      AlternateGridSlice,
      AlternateGridSliceDefaultPrimaryItemsItem,
      AlternateGridSliceDefaultPrimary,
      AlternateGridSliceImageRightPrimaryItemsItem,
      AlternateGridSliceImageRightPrimary,
      AlternateGridSliceVariation,
      AlternateGridSliceDefault,
      AlternateGridSliceImageRight,
      BackgroundVideoSlice,
      BackgroundVideoSliceDefaultPrimary,
      BackgroundVideoSliceVariation,
      BackgroundVideoSliceDefault,
      ContactSlice,
      ContactSliceDefaultPrimary,
      ContactSliceVariation,
      ContactSliceDefault,
      EventItemSlice,
      EventItemSliceDefaultPrimary,
      EventItemSliceVariation,
      EventItemSliceDefault,
      FeaturedReleasesSlice,
      FeaturedReleasesSliceDefaultPrimary,
      FeaturedReleasesSliceDefaultItem,
      FeaturedReleasesSliceVariation,
      FeaturedReleasesSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      InstagramGallerySlice,
      InstagramGallerySliceDefaultPrimary,
      InstagramGallerySliceVariation,
      InstagramGallerySliceDefault,
      MediaGallerySlice,
      MediaGallerySliceDefaultPrimary,
      MediaGallerySliceDefaultItem,
      MediaGallerySliceVariation,
      MediaGallerySliceDefault,
      ProductCarouselSlice,
      ProductCarouselSliceDefaultPrimary,
      ProductCarouselSliceDefaultItem,
      ProductCarouselSliceVariation,
      ProductCarouselSliceDefault,
      ReleaseCardSlice,
      ReleaseCardSliceDefaultPrimary,
      ReleaseCardSliceDefaultItem,
      ReleaseCardSliceVariation,
      ReleaseCardSliceDefault,
      UpcomingEventsSlice,
      UpcomingEventsSliceDefaultPrimary,
      UpcomingEventsSliceDefaultItem,
      UpcomingEventsSliceVariation,
      UpcomingEventsSliceDefault,
      VideoCarouselSlice,
      VideoCarouselSliceDefaultPrimary,
      VideoCarouselSliceDefaultItem,
      VideoCarouselSliceVariation,
      VideoCarouselSliceDefault,
    };
  }
}
