// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type AboutPageDocumentDataSlicesSlice = MediaGallerySlice;

/**
 * Content for about_page documents
 */
interface AboutPageDocumentData {
  /**
   * Page Title field in *about_page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: About
   * - **API ID Path**: about_page.page_title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  page_title: prismic.KeyTextField;

  /**
   * Hero Image field in *about_page*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * Artist Name field in *about_page*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Artist name
   * - **API ID Path**: about_page.artist_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist_name: prismic.KeyTextField;

  /**
   * Bio field in *about_page*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Artist biography
   * - **API ID Path**: about_page.bio
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  bio: prismic.RichTextField;

  /**
   * Slice Zone field in *about_page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutPageDocumentDataSlicesSlice>;
}

/**
 * about_page document from Prismic
 *
 * - **API ID**: `about_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<AboutPageDocumentData>,
    "about_page",
    Lang
  >;

/**
 * Content for event documents
 */
interface EventDocumentData {
  /**
   * date field in *event*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: event.date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * venue field in *event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.venue
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  venue: prismic.KeyTextField;

  /**
   * location field in *event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.location
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * ticket_link field in *event*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.ticket_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  ticket_link: prismic.KeyTextField;

  /**
   * description field in *event*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: event.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * event document from Prismic
 *
 * - **API ID**: `event`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type EventDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<EventDocumentData>, "event", Lang>;

type HomepageDocumentDataSlicesSlice =
  | HeroSectionSlice
  | FeaturedReleasesSlice
  | UpcomingEventsSlice
  | ReleaseCardSlice
  | EventItemSlice;

/**
 * Content for homepage documents
 */
interface HomepageDocumentData {
  /**
   * hero_image field in *homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.hero_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  hero_image: prismic.ImageField<never>;

  /**
   * featured_text field in *homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.featured_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  featured_text: prismic.RichTextField;

  /**
   * Slice Zone field in *homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice>;
}

/**
 * homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

/**
 * Item in *release → links*
 */
export interface ReleaseDocumentDataLinksItem {
  /**
   * platform_name field in *release → links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: release.links[].platform_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platform_name: prismic.KeyTextField;

  /**
   * url field in *release → links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: release.links[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *release → media_items*
 */
export interface ReleaseDocumentDataMediaItemsItem {
  /**
   * embed_code field in *release → media_items*
   *
   * - **Field Type**: Embed
   * - **Placeholder**: *None*
   * - **API ID Path**: release.media_items[].embed_code
   * - **Documentation**: https://prismic.io/docs/field#embed
   */
  embed_code: prismic.EmbedField;
}

/**
 * Content for release documents
 */
interface ReleaseDocumentData {
  /**
   * title field in *release*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: release.title
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * cover_image field in *release*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: release.cover_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * release_date field in *release*
   *
   * - **Field Type**: Date
   * - **Placeholder**: *None*
   * - **API ID Path**: release.release_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  release_date: prismic.DateField;

  /**
   * description field in *release*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: release.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * links field in *release*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: release.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<ReleaseDocumentDataLinksItem>>;

  /**
   * media_items field in *release*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: release.media_items[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  media_items: prismic.GroupField<Simplify<ReleaseDocumentDataMediaItemsItem>>;
}

/**
 * release document from Prismic
 *
 * - **API ID**: `release`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReleaseDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReleaseDocumentData>,
    "release",
    Lang
  >;

type ReleasesDocumentDataSlicesSlice = FeaturedReleasesSlice;

/**
 * Content for Releases documents
 */
interface ReleasesDocumentData {
  /**
   * Slice Zone field in *Releases*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ReleasesDocumentDataSlicesSlice> /**
   * Meta Title field in *Releases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: releases.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Releases*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: releases.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Releases*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: releases.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Releases document from Prismic
 *
 * - **API ID**: `releases`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ReleasesDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<
    Simplify<ReleasesDocumentData>,
    "releases",
    Lang
  >;

/**
 * Item in *site_settings → social_links*
 */
export interface SiteSettingsDocumentDataSocialLinksItem {}

type SiteSettingsDocumentDataSlicesSlice = never;

/**
 * Content for site_settings documents
 */
interface SiteSettingsDocumentData {
  /**
   * artist_name field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.artist_name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  artist_name: prismic.KeyTextField;

  /**
   * social_links field in *site_settings*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.social_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  social_links: prismic.GroupField<
    Simplify<SiteSettingsDocumentDataSocialLinksItem>
  >;

  /**
   * platform field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.platform
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platform: prismic.KeyTextField;

  /**
   * url field in *site_settings*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.url
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  url: prismic.KeyTextField;

  /**
   * Slice Zone field in *site_settings*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: site_settings.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<SiteSettingsDocumentDataSlicesSlice>;
}

/**
 * site_settings document from Prismic
 *
 * - **API ID**: `site_settings`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type SiteSettingsDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<SiteSettingsDocumentData>,
    "site_settings",
    Lang
  >;

export type AllDocumentTypes =
  | AboutPageDocument
  | EventDocument
  | HomepageDocument
  | ReleaseDocument
  | ReleasesDocument
  | SiteSettingsDocument;

/**
 * Primary content in *EventItem → Default → Primary*
 */
export interface EventItemSliceDefaultPrimary {
  /**
   * Event Date field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select event date
   * - **API ID Path**: event_item.default.primary.date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Venue field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Venue name
   * - **API ID Path**: event_item.default.primary.venue
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  venue: prismic.KeyTextField;

  /**
   * Location field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, State/Country
   * - **API ID Path**: event_item.default.primary.location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Ticket Link field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to tickets
   * - **API ID Path**: event_item.default.primary.ticket_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ticket_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Description field in *EventItem → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Event description
   * - **API ID Path**: event_item.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for EventItem Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventItemSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<EventItemSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *EventItem*
 */
type EventItemSliceVariation = EventItemSliceDefault;

/**
 * EventItem Shared Slice
 *
 * - **API ID**: `event_item`
 * - **Description**: EventItem
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type EventItemSlice = prismic.SharedSlice<
  "event_item",
  EventItemSliceVariation
>;

/**
 * Primary content in *FeaturedReleases → Default → Primary*
 */
export interface FeaturedReleasesSliceDefaultPrimary {
  /**
   * Releases field in *FeaturedReleases → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Featured Releases
   * - **API ID Path**: featured_releases.default.primary.releases
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  releases: prismic.KeyTextField;

  /**
   * Section Description field in *FeaturedReleases → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description of the releases section
   * - **API ID Path**: featured_releases.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;
}

/**
 * Primary content in *FeaturedReleases → Items*
 */
export interface FeaturedReleasesSliceDefaultItem {
  /**
   * Title field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Release title
   * - **API ID Path**: featured_releases.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Cover Image field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: featured_releases.items[].cover_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Release Date field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select release date
   * - **API ID Path**: featured_releases.items[].release_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  release_date: prismic.DateField;

  /**
   * Description field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Release description
   * - **API ID Path**: featured_releases.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Platform Name field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Spotify, Apple Music
   * - **API ID Path**: featured_releases.items[].platform_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platform_name: prismic.KeyTextField;

  /**
   * Platform URL field in *FeaturedReleases → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to platform
   * - **API ID Path**: featured_releases.items[].platform_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  platform_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for FeaturedReleases Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedReleasesSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<FeaturedReleasesSliceDefaultPrimary>,
  Simplify<FeaturedReleasesSliceDefaultItem>
>;

/**
 * Slice variation for *FeaturedReleases*
 */
type FeaturedReleasesSliceVariation = FeaturedReleasesSliceDefault;

/**
 * FeaturedReleases Shared Slice
 *
 * - **API ID**: `featured_releases`
 * - **Description**: FeaturedReleases
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type FeaturedReleasesSlice = prismic.SharedSlice<
  "featured_releases",
  FeaturedReleasesSliceVariation
>;

/**
 * Primary content in *HeroSection → Default → Primary*
 */
export interface HeroSectionSliceDefaultPrimary {
  /**
   * Title field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Main headline
   * - **API ID Path**: hero_section.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Subtitle field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Subtitle text
   * - **API ID Path**: hero_section.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  subtitle: prismic.KeyTextField;

  /**
   * Description field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description text
   * - **API ID Path**: hero_section.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;

  /**
   * Video URL (YouTube/Vimeo) field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: https://www.youtube.com/watch?v=... or https://vimeo.com/...
   * - **API ID Path**: hero_section.default.primary.video_url
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  video_url: prismic.KeyTextField;

  /**
   * Background Image (fallback) field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: hero_section.default.primary.background_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  background_image: prismic.ImageField<never>;

  /**
   * CTA Text field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Call to action text
   * - **API ID Path**: hero_section.default.primary.cta_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  cta_text: prismic.KeyTextField;

  /**
   * CTA Link field in *HeroSection → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Call to action link
   * - **API ID Path**: hero_section.default.primary.cta_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  cta_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Default variation for HeroSection Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<HeroSectionSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *HeroSection*
 */
type HeroSectionSliceVariation = HeroSectionSliceDefault;

/**
 * HeroSection Shared Slice
 *
 * - **API ID**: `hero_section`
 * - **Description**: HeroSection
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type HeroSectionSlice = prismic.SharedSlice<
  "hero_section",
  HeroSectionSliceVariation
>;

/**
 * Primary content in *MediaGallery → Default → Primary*
 */
export interface MediaGallerySliceDefaultPrimary {
  /**
   * Gallery Title field in *MediaGallery → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Gallery title
   * - **API ID Path**: media_gallery.default.primary.gallery_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  gallery_title: prismic.KeyTextField;
}

/**
 * Primary content in *MediaGallery → Items*
 */
export interface MediaGallerySliceDefaultItem {
  /**
   * Title field in *MediaGallery → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Media item title
   * - **API ID Path**: media_gallery.items[].title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Image field in *MediaGallery → Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: media_gallery.items[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Video URL field in *MediaGallery → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Video URL
   * - **API ID Path**: media_gallery.items[].video_url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  video_url: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Embed Code field in *MediaGallery → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Paste embed code
   * - **API ID Path**: media_gallery.items[].embed_code
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  embed_code: prismic.RichTextField;
}

/**
 * Default variation for MediaGallery Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaGallerySliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<MediaGallerySliceDefaultPrimary>,
  Simplify<MediaGallerySliceDefaultItem>
>;

/**
 * Slice variation for *MediaGallery*
 */
type MediaGallerySliceVariation = MediaGallerySliceDefault;

/**
 * MediaGallery Shared Slice
 *
 * - **API ID**: `media_gallery`
 * - **Description**: MediaGallery
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type MediaGallerySlice = prismic.SharedSlice<
  "media_gallery",
  MediaGallerySliceVariation
>;

/**
 * Primary content in *ReleaseCard → Default → Primary*
 */
export interface ReleaseCardSliceDefaultPrimary {
  /**
   * Title field in *ReleaseCard → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Release title
   * - **API ID Path**: release_card.default.primary.title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  title: prismic.KeyTextField;

  /**
   * Cover Image field in *ReleaseCard → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: release_card.default.primary.cover_image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  cover_image: prismic.ImageField<never>;

  /**
   * Release Date field in *ReleaseCard → Default → Primary*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select release date
   * - **API ID Path**: release_card.default.primary.release_date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  release_date: prismic.DateField;

  /**
   * Description field in *ReleaseCard → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Release description
   * - **API ID Path**: release_card.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Primary content in *ReleaseCard → Items*
 */
export interface ReleaseCardSliceDefaultItem {
  /**
   * Platform Name field in *ReleaseCard → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: e.g., Spotify, Apple Music
   * - **API ID Path**: release_card.items[].platform_name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  platform_name: prismic.KeyTextField;

  /**
   * URL field in *ReleaseCard → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to platform
   * - **API ID Path**: release_card.items[].url
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  url: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Default variation for ReleaseCard Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReleaseCardSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<ReleaseCardSliceDefaultPrimary>,
  Simplify<ReleaseCardSliceDefaultItem>
>;

/**
 * Slice variation for *ReleaseCard*
 */
type ReleaseCardSliceVariation = ReleaseCardSliceDefault;

/**
 * ReleaseCard Shared Slice
 *
 * - **API ID**: `release_card`
 * - **Description**: ReleaseCard
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type ReleaseCardSlice = prismic.SharedSlice<
  "release_card",
  ReleaseCardSliceVariation
>;

/**
 * Primary content in *UpcomingEvents → Default → Primary*
 */
export interface UpcomingEventsSliceDefaultPrimary {
  /**
   * Section Title field in *UpcomingEvents → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Upcoming Events
   * - **API ID Path**: upcoming_events.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  section_title: prismic.KeyTextField;

  /**
   * Section Description field in *UpcomingEvents → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Description of upcoming events
   * - **API ID Path**: upcoming_events.default.primary.section_description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  section_description: prismic.RichTextField;

  /**
   * View All Text field in *UpcomingEvents → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: View All Events
   * - **API ID Path**: upcoming_events.default.primary.view_all_text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  view_all_text: prismic.KeyTextField;

  /**
   * View All Link field in *UpcomingEvents → Default → Primary*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to all events page
   * - **API ID Path**: upcoming_events.default.primary.view_all_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  view_all_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;
}

/**
 * Primary content in *UpcomingEvents → Items*
 */
export interface UpcomingEventsSliceDefaultItem {
  /**
   * Event Date field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Date
   * - **Placeholder**: Select event date
   * - **API ID Path**: upcoming_events.items[].date
   * - **Documentation**: https://prismic.io/docs/field#date
   */
  date: prismic.DateField;

  /**
   * Venue field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Venue name
   * - **API ID Path**: upcoming_events.items[].venue
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  venue: prismic.KeyTextField;

  /**
   * Location field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: City, State/Country
   * - **API ID Path**: upcoming_events.items[].location
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  location: prismic.KeyTextField;

  /**
   * Ticket Link field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Link
   * - **Placeholder**: Link to tickets
   * - **API ID Path**: upcoming_events.items[].ticket_link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  ticket_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Description field in *UpcomingEvents → Items*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: Event description
   * - **API ID Path**: upcoming_events.items[].description
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  description: prismic.RichTextField;
}

/**
 * Default variation for UpcomingEvents Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UpcomingEventsSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<UpcomingEventsSliceDefaultPrimary>,
  Simplify<UpcomingEventsSliceDefaultItem>
>;

/**
 * Slice variation for *UpcomingEvents*
 */
type UpcomingEventsSliceVariation = UpcomingEventsSliceDefault;

/**
 * UpcomingEvents Shared Slice
 *
 * - **API ID**: `upcoming_events`
 * - **Description**: UpcomingEvents
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type UpcomingEventsSlice = prismic.SharedSlice<
  "upcoming_events",
  UpcomingEventsSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutPageDocument,
      AboutPageDocumentData,
      AboutPageDocumentDataSlicesSlice,
      EventDocument,
      EventDocumentData,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataSlicesSlice,
      ReleaseDocument,
      ReleaseDocumentData,
      ReleaseDocumentDataLinksItem,
      ReleaseDocumentDataMediaItemsItem,
      ReleasesDocument,
      ReleasesDocumentData,
      ReleasesDocumentDataSlicesSlice,
      SiteSettingsDocument,
      SiteSettingsDocumentData,
      SiteSettingsDocumentDataSocialLinksItem,
      SiteSettingsDocumentDataSlicesSlice,
      AllDocumentTypes,
      EventItemSlice,
      EventItemSliceDefaultPrimary,
      EventItemSliceVariation,
      EventItemSliceDefault,
      FeaturedReleasesSlice,
      FeaturedReleasesSliceDefaultPrimary,
      FeaturedReleasesSliceDefaultItem,
      FeaturedReleasesSliceVariation,
      FeaturedReleasesSliceDefault,
      HeroSectionSlice,
      HeroSectionSliceDefaultPrimary,
      HeroSectionSliceVariation,
      HeroSectionSliceDefault,
      MediaGallerySlice,
      MediaGallerySliceDefaultPrimary,
      MediaGallerySliceDefaultItem,
      MediaGallerySliceVariation,
      MediaGallerySliceDefault,
      ReleaseCardSlice,
      ReleaseCardSliceDefaultPrimary,
      ReleaseCardSliceDefaultItem,
      ReleaseCardSliceVariation,
      ReleaseCardSliceDefault,
      UpcomingEventsSlice,
      UpcomingEventsSliceDefaultPrimary,
      UpcomingEventsSliceDefaultItem,
      UpcomingEventsSliceVariation,
      UpcomingEventsSliceDefault,
    };
  }
}
