// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  hero_section: dynamic(() => import("./HeroSection")),
  featured_releases: dynamic(() => import("./FeaturedReleases")),
  upcoming_events: dynamic(() => import("./UpcomingEvents")),
  release_card: dynamic(() => import("./ReleaseCard")),
  event_item: dynamic(() => import("./EventItem")),
  media_gallery: dynamic(() => import("./MediaGallery")),
};
